# -*- coding: utf-8 -*-
"""flask.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CIiFfSqe74qLeMVBT6kysrdoj4lKlvkK
"""

# STEP 1 loading the required packages

from __future__ import division, print_function

import os

import numpy as np

from keras.models import load_model

import tensorflow as tf



from flask import Flask

from flask import request

from flask import render_template

from werkzeug.utils import secure_filename

from keras.models import model_from_json

# STEP 2 Initializing graph, loading the model and model graph, initializing the Flask app using the load_model from keras 
global graph

graph=tf.compat.v1.get_default_graph()

# defining a flask app
app=Flask(__name__)



# STEP 3 Configuring the Home page

@app.route('/', methods=['GET'])
def index():
    # Main page
    return render_template('index.html')

#@app.route('/predict', methods=['GET','POST'])

# STEP iv - Pre-Processing the Frame and run

@app.route('/predict', methods=['GET','POST'])
def upload():
    if request.method=='POST':
        #Get the file from post request
        f=request.files['image']

        #Save the files to ./uploads
        
        basepath=os.path.dirname(__file__)
        file_path=os.path.join(
            basepath, 'uploads', secure_filename(f.filename))
        f.save(file_path)
        img=tf.keras.preprocessing.image.load_img(file_path, target_size=(224,224))
        
        x=tf.keras.preprocessing.image.img_to_array(img)
        x=np.expand_dims(x,axis=0)
        
        with graph.as_default():
            #Loading the Trained model
            json_file=open('final_model.json','r')
            loaded_model_json=json_file.read()

            json_file.close()

            loaded_model=model_from_json(loaded_model_json)

            loaded_model.load_weights("final_model.h5")
            loaded_model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

            print('Model loaded.Check http://127.0.0.1:5000/')
            predict_x=loaded_model.predict(x) 
            preds=np.argmax(predict_x,axis=1)
        #   preds=loaded_model.predict_classes(x)
        found=["PANGOLINS, sometimes known as scaly anteaters, are mammals of the order Pholidota. The one extant family, the Manidae, has three genera: Manis, Phataginus, and Smutsia. Manis comprises the four species found in Asia, while Phataginus and Smutsia include two species each, all found in sub-Saharan Africa.  When in danger, the pangolin can roll into a ball, exposing only the sharp scales on the tail which can be used to lash out. The shy, harmless pangolin is becoming increasingly well known for one reason: It's believed to be the world's most trafficked non-human mammal. Eight species of pangolins are found on two continents. They range from Vulnerable to Critically Endangered.",
               "THE WHITE DEER, They are considered to be messengers from the otherworld in some Celtic mythology, In European and Celtic mythology white deer are believed to be supernatural, and the Arthurian legends include a magical white stag and many countries do have their prophesis and stories. is a medium-sized deer native to North America, Central America, and South America as far south as Peru and Bolivia.",
               "The SPOON-BILLED SANDPIPER breeds in far northeastern Russia along the Bering Sea coast of the Chukotsk peninsula and southwards down the Kamchatka peninsula, Originating along the Chukotsk Peninsula in Russia, the Spoon-billed Sandpiper is facing extinction. The birds migrate through 8,000 kilometres of coastline on the East Asian-Australasian Flyway and breed only in lagoon spits and areas with crowberry-lichen vegetation. This bird is critically endangered, with a current population of fewer than 2500 – probably fewer than 1000 – mature individuals. The main threats to its survival are habitat loss on its breeding grounds and loss of tidal flats through its migratory and wintering range. First records of Spoon-billed Sandpiper Calidris pygmeus in the Indian Sundarbans delta, West Bengal.",
               "The GREAT INDIAN BUSTARD is a bustard found on the Indian Subcontinent. A large bird with a horizontal body and long bare legs, giving it an ostrich like appearance, this bird is among the heaviest of the flying birds. Is CRITICALLY ENDANGERED",
               "CYPRIPEDIUM CALCEOLUS, commonly known as the Lady’s Slipper orchid or Yellow Lady Slipper orchid, is a perennial flowering plant from the botanical family Orchidaceae and genus Cypripedium. The Cypripedium genus consists of 58 species of hardy orchids that usually thrive in temperate and subtropical climates. The genus Mexipedium consists of a single species, M. xerophyticum, endemic to a small region of Oaxaca, Mexico. The plants grow on dry cliff faces and spread by runners. The tiny flowers are white with a pale pink central column. The plant is considered critically endangered. It serves as a Tranquilizer. Cures Muscle Tension, Headaches, Antisplasmodic, Nerve Pain. Drinking tinctures of lady’s slipper roots was a popular remedy for insomnia, anxiety, or general emotional tension. Native Americans generally collected the roots in the fall or early spring, dried them out and ground them into a powder.",
               "AMORPHOPHALLUS TITANUM, the titan arum or 'Corpse flower', flowering plant in family Araceae. Its a rarest flower on earth. takes around 7 yrs to grow before it blooms, nicknamed as Corspe flower as it smells like a ROTTEN FLESH when it blooms, which is indeed produced to attract the pollinators that love to freed & breed on flesh. Grows only in Sumatra Rainforests, is endangered due to deforestationand land degradation. Isn't toxic if not prepared properly as it contains Calcium oxalate crystals. Corm and leaf stalks are boiled and eaten, to treat Stomach ailments, fever, swelling, diarrhea, tumor supression, detoxification, blood stasis allevation and phlegm liquefaction, hernia and other haematological & skin disorders"]
        text=found[preds[0]]
        return text
        
#if __name__ == "__main__": from waitress import serve serve(app, host="127.0.0.1", port=8017)
#if __name__ == '__main__':  app.run(host='127.0.0.1', port=8017)
if __name__=='__main__':
  app.run(threaded=False)